      <ul id="nav">
		<li class="topLevel"><a href="<?php echo $this->url( array(), 'index' ) ?>">Accueil</a></li>
		<li class="topLevel"><a href="/User/index/adduser">Créer user</a></li>
		<li class="topLevel"><a href="<?php echo $this->url( array( 'id' => 4, 'nom' => 'tesstdyheght'), 'userById2' ) ?>">User</a></li>
		<li class="topLevel"><a href="<?php echo $this->url( array(), 'userList' ) ?>">Liste</a></li>
      </ul>
	  
