<?php 
$ext  = APPLICATION_ENV === 'production' ? '.min.css' : '.css';
$this->headLink()->appendStylesheet( '/css/error' . $ext );
echo $this->Doctype() 
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle()   . PHP_EOL; ?>
<?php echo $this->headMeta()    . PHP_EOL; ?>
<?php echo $this->headScript()  . PHP_EOL; ?>
<?php echo $this->headLink()    . PHP_EOL; ?>
<link rel="icon" type="image/png" href="/favicon.png" />
<!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" /><![endif]-->
</head>
<body>
<div id="erroWrapper">
<?php echo $this->layout()->content; ?>
</div>
<?php echo $this->inlineScript() . PHP_EOL; ?>
</body>
</html>